### ISSUE TITLE
NewRelic provider is not transmitting API key correctly

### ISSUE THREAD

**Issue by HansMoleman** [pulumi/pulumi-newrelic#7]
When using the New Relic provider, the API that is passed in is not being honored. It appears that regardless of what API is passed in, Pulumi will attempt to grab the API key from config
 
```
const nrprovider = new newrelic.Provider("bngo-test", { apiKey: "test" });

const fooAlertPolicy = new newrelic.AlertPolicy("foo", {});
const fooInfraAlertCondition = new newrelic.InfraAlertCondition("foo", {
    comparison: "above",
    critical: {
        duration: 25,
        timeFunction: "all",
        value: 90,
    },
    event: "StorageSample",
    policyId: 100,
    select: "diskUsedPercent",
    type: "infra_metric",
    where: "(`hostname` LIKE '%frontend%')",
}, {provider: nrprovider});
```

and in the error, we can see that Pulumi is attempting to pull the key from config:

```
Diagnostics:
  newrelic:index:AlertPolicy (foo):
    error: 1 error occurred:
        * missing required configuration key "newrelic:apiKey":
    Set a value using the command `pulumi config set newrelic:apiKey <value>`.
```

**Comment by ellismg** [comment]
Can you confirm what version of the package you are using by looking at the version field in `package.json` in `node_modules/@pulumi/newrelic`?  If it is earlier than 0.18.1, can you please try to update to that version?

**Comment by stack72** [comment]
Hi @HansMoleman 

So I completely missed this the first time, but you have no passed the provider to your AlertPolicy resource which is why it’s throwing an error. If you don’t pass a provider, it will try and use the default provider which reads from the config

Thanks to @ellismg for spotting this and recreating the error condition and then showing me the solution

Sorry for the wait here

Paul
